Repository primefaces/primeng, pull requests merged in 2018-08, with the labels that each got.

#6184 Inline style to the calendar
  src/app/components/calendar/calendar.ts
Labels: new feature

#6356 FileUpload accept should be case insensitive
  src/app/components/fileupload/fileupload.ts
Labels: defect

#6240 Update dialog.ts, fixes for 5974 and 5336
  src/app/components/dialog/dialog.ts
Labels: pending-review
