Repository primefaces/primeng, pull requests merged in 2018-04, with the labels that each got.

#5473 Fix style of floating label and (Chromes) autofill
  src/app/components/inputtext/inputtext.css
Labels: defect

#5494 Extend DomHandler with new method
  src/app/components/dom/domhandler.ts
Labels: enhancement

#5503 Added loading and loadingIcon to DataView
  src/app/components/dataview/dataview.css
  src/app/components/dataview/dataview.ts
Labels: new feature
