Repository primefaces/primeng, pull requests merged in 2018-03, with the labels that each got.

#5237 InputMask component's value not synced
  src/app/components/inputmask/inputmask.ts
Labels: defect

#5212 Preselection by value for SelectButton
  src/app/components/selectbutton/selectbutton.spec.ts
  src/app/components/selectbutton/selectbutton.ts
Labels: enhancement

#5087 Add visible flag to panelmenu
  src/app/components/panelmenu/panelmenu.ts
Labels: enhancement

#5278 Add onYearChange to Calendar
  src/app/components/calendar/calendar.ts
  src/app/showcase/components/calendar/calendardemo.html
Labels: new feature

#5317 RTL Support for Scrolling Table
  src/app/components/table/table.ts
Labels: enhancement

#5440 MegaMenu ignores visible property of MenuItem API
  src/app/components/megamenu/megamenu.ts
Labels: defect

#5357 #2993 - Spinner: decimals are separated by the thousand separator
  src/app/components/spinner/spinner.spec.ts
  src/app/components/spinner/spinner.ts
Labels: defect

#5421 Add TrackBy to OrderList
  src/app/components/orderlist/orderlist.ts
Labels: enhancement

#5363 Implement effectDuration for Galleria
  src/app/components/galleria/galleria.ts
Labels: enhancement

#5408 Wrong return value in calendar
  src/app/components/calendar/calendar.ts
Labels: defect
