Repository primefaces/primeng, pull requests merged in 2019-05, with the labels that each got.

#7602 Possibility to use default message
  src/app/components/common/confirmation.ts
Labels: enhancement

#7660 #7149 Clicking icon in advanced fileupload button does not open filechooser
  src/app/components/fileupload/fileupload.css
Labels: defect

#7587 Added headerFacet for to display header content in Multiselect
  src/app/components/multiselect/multiselect.ts
Labels: new feature
