Repository primefaces/primeng, pull requests merged in 2020-03, with the labels that each got.

#8563 FileUpload size formatting is incorrect
  src/app/components/fileupload/fileupload.ts
Labels: defect

#8414 Accept and Reject icons to Confirmation
  src/app/components/api/confirmation.ts
  src/app/components/confirmdialog/confirmdialog.ts
Labels: enhancement

#8524 ConfirmDialog close via service feature
  src/app/components/api/confirmationservice.ts
  src/app/components/confirmdialog/confirmdialog.ts
Labels: new feature
