Repository primefaces/primeng, pull requests merged in 2022-10, with the labels that each got.

#12054 Autocomplete | Value remains the old when entered text changed
  src/app/components/autocomplete/autocomplete.ts
Labels: need revision

#12038 fix(primeng/p-chips): not unfocus input when disabled for firefox
  src/app/components/chips/chips.ts
Labels: pending-review, need revision

#12051 fix(primeng/p-treeSelect): reset partial selected tree item
  src/app/components/treeselect/treeselect.ts
Labels: pending-review

#12042 fix issue #11931
  src/app/components/table/table.ts
Labels: need revision

#12056 Fixed #11931 - Table | ReferenceError: Cannot access 'ColumnFilter' before initialization
  src/app/components/table/table.ts
Labels: need revision

#12066 Fixed #12025 - Sidebar Header Template
  src/app/components/sidebar/sidebar.css
  src/app/components/sidebar/sidebar.ts
  src/app/showcase/components/sidebar/sidebardemo.html
Labels: need revision

#12069 added panelStyleClass
  src/app/components/password/password.ts
  src/app/components/treeselect/treeselect.ts
  src/app/showcase/components/multiselect/multiselectdemo.html
  src/app/showcase/components/password/passworddemo.html
  src/app/showcase/components/treeselect/treeselectdemo.html
Labels: need revision

#12044 Fixed #12031 - Component: Responsive Overlay
  src/app/components/api/primengconfig.ts
  src/app/components/dropdown/dropdown.css
  src/app/components/dropdown/dropdown.ts
  src/app/components/overlay/ng-package.json
  src/app/components/overlay/overlay.css
  src/app/components/overlay/overlay.ts
  src/app/components/overlay/public_api.ts
Labels: need revision

#12078 Fixed #12077 - InputNumber | Support highlight on focus property
  src/app/components/dom/domhandler.ts
  src/app/components/inputnumber/inputnumber.ts
Labels: need revision

#12096 Refactor #12031 - Component: Responsive Overlay
  src/app/components/api/overlayoptions.ts
  src/app/components/api/primengconfig.ts
  src/app/components/api/public_api.ts
  src/app/components/dom/domhandler.ts
  src/app/components/dropdown/dropdown.css
  src/app/components/dropdown/dropdown.ts
  src/app/components/overlay/overlay.css
  src/app/components/overlay/overlay.ts
  src/app/components/scroller/scroller.ts
Labels: pending-review

#12098 Use explicit type for iconPos in components fixes #12097
  src/app/components/badge/badge.ts
  src/app/components/button/button.ts
  src/app/components/panel/panel.ts
  src/app/components/splitbutton/splitbutton.ts
  src/app/components/togglebutton/togglebutton.ts
  src/app/showcase/components/panel/paneldemo.html
Labels: need revision

#12086 Fixed Bad Typo in Showcase for p-dataview
  src/app/showcase/components/dataview/dataviewdemo.html
Labels: need revision
