Repository primefaces/primeng, pull requests merged in 2022-11, with the labels that each got.

#12119 Fixed #12116 - TreeSelect | Add p-overlay
  src/app/components/tree/tree.ts
  src/app/components/treeselect/treeselect.css
  src/app/components/treeselect/treeselect.ts
Labels: need revision

#12118 Fixed #12117 Sidebar | Add footer template
  src/app/components/sidebar/sidebar.ts
  src/app/showcase/components/sidebar/sidebardemo.html
  src/assets/components/themes/arya-blue/theme.css
  src/assets/components/themes/arya-green/theme.css
  src/assets/components/themes/arya-orange/theme.css
  src/assets/components/themes/arya-purple/theme.css
  src/assets/components/themes/bootstrap4-dark-blue/theme.css
  src/assets/components/themes/bootstrap4-dark-purple/theme.css
  src/assets/components/themes/bootstrap4-light-blue/theme.css
  src/assets/components/themes/bootstrap4-light-purple/theme.css
  src/assets/components/themes/fluent-light/theme.css
  src/assets/components/themes/lara-dark-blue/theme.css
  src/assets/components/themes/lara-dark-indigo/theme.css
  src/assets/components/themes/lara-dark-purple/theme.css
  src/assets/components/themes/lara-dark-teal/theme.css
  src/assets/components/themes/lara-light-blue/theme.css
  src/assets/components/themes/lara-light-indigo/theme.css
  src/assets/components/themes/lara-light-purple/theme.css
  src/assets/components/themes/lara-light-teal/theme.css
  src/assets/components/themes/luna-amber/theme.css
  src/assets/components/themes/luna-blue/theme.css
  src/assets/components/themes/luna-green/theme.css
  src/assets/components/themes/luna-pink/theme.css
  src/assets/components/themes/md-dark-deeppurple/theme.css
  src/assets/components/themes/md-dark-indigo/theme.css
  src/assets/components/themes/md-light-deeppurple/theme.css
  src/assets/components/themes/md-light-indigo/theme.css
  src/assets/components/themes/mdc-dark-deeppurple/theme.css
  src/assets/components/themes/mdc-dark-indigo/theme.css
  src/assets/components/themes/mdc-light-deeppurple/theme.css
  src/assets/components/themes/mdc-light-indigo/theme.css
  src/assets/components/themes/nova-accent/theme.css
  src/assets/components/themes/nova-alt/theme.css
  src/assets/components/themes/nova/theme.css
  src/assets/components/themes/rhea/theme.css
  src/assets/components/themes/saga-blue/theme.css
  src/assets/components/themes/saga-green/theme.css
  src/assets/components/themes/saga-orange/theme.css
  src/assets/components/themes/saga-purple/theme.css
  src/assets/components/themes/tailwind-light/theme.css
  src/assets/components/themes/vela-blue/theme.css
  src/assets/components/themes/vela-green/theme.css
  src/assets/components/themes/vela-orange/theme.css
  src/assets/components/themes/vela-purple/theme.css
Labels: need revision

#12004 Fixed #11918 - DataTable: Multiple sorting with Date field as first sort
  src/app/components/table/table.ts
  src/app/components/utils/objectutils.ts
Labels: need revision

#11416 fix(primeng/p-password): incorrect class assignment for `true` value of `toggleMask` in the password component.
  src/app/components/password/password.ts
Labels: pending-review

#12092 feat(primeng/p-chips): update separator interface
  src/app/components/api/chips-separator.ts
  src/app/components/api/public_api.ts
  src/app/components/chips/chips.ts
  src/app/showcase/components/chips/chipsdemo.html
  src/app/showcase/components/chips/chipsdemo.ts
Labels: breaking-change

#12123 #12084 Menu icon visible
  src/app/components/menubar/menubar.ts
Labels: need revision

#11991 Fixed #11902 - inputNumber | minFractionDigits fails if set to "0" when using with a suffix
  .vscode/extensions.json
  .vscode/settings.team.json
  src/app/components/inputnumber/inputnumber.ts
Labels: need revision

#11904 Fixed #9842 - Button | Renders empty label when the label is not defined
  src/assets/components/themes/arya-blue/theme.css
  src/assets/components/themes/arya-green/theme.css
  src/assets/components/themes/arya-orange/theme.css
  src/assets/components/themes/arya-purple/theme.css
  src/assets/components/themes/bootstrap4-dark-blue/theme.css
  src/assets/components/themes/bootstrap4-dark-purple/theme.css
  src/assets/components/themes/bootstrap4-light-blue/theme.css
  src/assets/components/themes/bootstrap4-light-purple/theme.css
  src/assets/components/themes/fluent-light/theme.css
  src/assets/components/themes/lara-dark-blue/theme.css
  src/assets/components/themes/lara-dark-indigo/theme.css
  src/assets/components/themes/lara-dark-purple/theme.css
  src/assets/components/themes/lara-dark-teal/theme.css
  src/assets/components/themes/lara-light-blue/theme.css
  src/assets/components/themes/lara-light-indigo/theme.css
  src/assets/components/themes/lara-light-purple/theme.css
  src/assets/components/themes/lara-light-teal/theme.css
  src/assets/components/themes/luna-amber/theme.css
  src/assets/components/themes/luna-blue/theme.css
  src/assets/components/themes/luna-green/theme.css
  src/assets/components/themes/luna-pink/theme.css
  src/assets/components/themes/md-dark-deeppurple/theme.css
  src/assets/components/themes/md-dark-indigo/theme.css
  src/assets/components/themes/md-light-deeppurple/theme.css
  src/assets/components/themes/md-light-indigo/theme.css
  src/assets/components/themes/mdc-dark-deeppurple/theme.css
  src/assets/components/themes/mdc-dark-indigo/theme.css
  src/assets/components/themes/mdc-light-deeppurple/theme.css
  src/assets/components/themes/mdc-light-indigo/theme.css
  src/assets/components/themes/nova-accent/theme.css
  src/assets/components/themes/nova-alt/theme.css
  src/assets/components/themes/nova/theme.css
  src/assets/components/themes/rhea/theme.css
  src/assets/components/themes/saga-blue/theme.css
  src/assets/components/themes/saga-green/theme.css
  src/assets/components/themes/saga-orange/theme.css
  src/assets/components/themes/saga-purple/theme.css
  src/assets/components/themes/tailwind-light/theme.css
  src/assets/components/themes/vela-blue/theme.css
  src/assets/components/themes/vela-green/theme.css
  src/assets/components/themes/vela-orange/theme.css
  src/assets/components/themes/vela-purple/theme.css
Labels: need revision

#12200 Fixed #12176 - pAutoFocus | Does not work if element has 'p-disabled' class
  src/app/components/autofocus/autofocus.ts
Labels: Resolution: Needs Revision

#12040 fix(primeng/p-fileUpload): render uploadLabel for `basic` mode when is exist
  src/app/components/fileupload/fileupload.ts
Labels: Resolution: Needs Revision

#12228 Fixed wrong style classes in showcase of toast component
  src/app/showcase/components/toast/toastdemo.html
Labels: Component: Documentation

#12234 Fix to typo in speed dial documentation
  src/app/showcase/components/speeddial/speeddialdemo.html
Labels: Resolution: Needs Revision

#12238 autoResize is a wrong type in docs
  src/app/showcase/components/inputtextarea/inputtextareademo.html
Labels: Resolution: Needs Revision

#12271 V15
  package.json
  src/app/components/checkbox/checkbox.spec.ts
  src/app/components/checkbox/checkbox.ts
  src/app/components/fileupload/fileupload.ts
  src/app/components/inputmask/inputmask.spec.ts
  src/app/components/inputmask/inputmask.ts
  src/app/components/package.json
  src/app/components/radiobutton/radiobutton.spec.ts
  src/app/showcase/app.footer.component.ts
  src/test.ts
  src/versions.json
  tsconfig.json
Labels: Resolution: Needs Revision

#12297 Fixed #12273 - Remove condition in hide
  src/app/components/overlaypanel/overlaypanel.ts
Labels: Resolution: Needs Revision

#12301 Fixed #12216 - ToggleButton | Label of basic button is unexpectedly s…
  src/app/components/togglebutton/togglebutton.ts
Labels: Resolution: Needs Revision
