Repository primefaces/primeng, pull requests merged in 2022-12, with the labels that each got.

#12158 fix #12157 only show emptyMessage if dataView is not loading
  src/app/components/dataview/dataview.ts
Labels: Resolution: Needs Revision

#12311 Add output to TabMenu on item selection
  src/app/components/tabmenu/tabmenu.ts
  src/app/showcase/components/tabmenu/tabmenudemo.html
Labels: Resolution: Needs Revision

#10947 fixed #10595; Remove duplicated dropdown's property in doc
  src/app/showcase/components/dropdown/dropdowndemo.html
Labels: Resolution: Stale

#12422 Fix: #12419 - Remove extra bottom spacing.
  src/app/components/chips/chips.ts
Labels: Resolution: Needs Revision

#12371 Fixed #12364, Fixed #12365, Fixed #12366
  src/app/components/toolbar/toolbar.css
  src/app/components/toolbar/toolbar.ts
  src/app/showcase/components/toolbar/toolbardemo.html
  src/assets/components/themes/arya-blue/theme.css
  src/assets/components/themes/arya-green/theme.css
  src/assets/components/themes/arya-orange/theme.css
  src/assets/components/themes/arya-purple/theme.css
  src/assets/components/themes/bootstrap4-dark-blue/theme.css
  src/assets/components/themes/bootstrap4-dark-purple/theme.css
  src/assets/components/themes/bootstrap4-light-blue/theme.css
  src/assets/components/themes/bootstrap4-light-purple/theme.css
  src/assets/components/themes/fluent-light/theme.css
  src/assets/components/themes/lara-dark-blue/theme.css
  src/assets/components/themes/lara-dark-indigo/theme.css
  src/assets/components/themes/lara-dark-purple/theme.css
  src/assets/components/themes/lara-dark-teal/theme.css
  src/assets/components/themes/lara-light-blue/theme.css
  src/assets/components/themes/lara-light-indigo/theme.css
  src/assets/components/themes/lara-light-purple/theme.css
  src/assets/components/themes/lara-light-teal/theme.css
  src/assets/components/themes/luna-amber/theme.css
  src/assets/components/themes/luna-blue/theme.css
  src/assets/components/themes/luna-green/theme.css
  src/assets/components/themes/luna-pink/theme.css
  src/assets/components/themes/md-dark-deeppurple/theme.css
  src/assets/components/themes/md-dark-indigo/theme.css
  src/assets/components/themes/md-light-deeppurple/theme.css
  src/assets/components/themes/md-light-indigo/theme.css
  src/assets/components/themes/mdc-dark-deeppurple/theme.css
  src/assets/components/themes/mdc-dark-indigo/theme.css
  src/assets/components/themes/mdc-light-deeppurple/theme.css
  src/assets/components/themes/mdc-light-indigo/theme.css
  src/assets/components/themes/nova-accent/theme.css
  src/assets/components/themes/nova-alt/theme.css
  src/assets/components/themes/nova/theme.css
  src/assets/components/themes/rhea/theme.css
  src/assets/components/themes/saga-blue/theme.css
  src/assets/components/themes/saga-green/theme.css
  src/assets/components/themes/saga-orange/theme.css
  src/assets/components/themes/saga-purple/theme.css
  src/assets/components/themes/tailwind-light/theme.css
  src/assets/components/themes/vela-blue/theme.css
  src/assets/components/themes/vela-green/theme.css
  src/assets/components/themes/vela-orange/theme.css
  src/assets/components/themes/vela-purple/theme.css
Labels: Core Team

#12000 TabMenu route link matching fixed #11999
  src/app/components/tabmenu/tabmenu.ts
Labels: Status: Pending Review
