Repository primefaces/primeng, pull requests merged in 2022-09, with the labels that each got.

#11885 Fixed #11884 - FileUploader | StyleClass support for buttons
  src/app/components/fileupload/fileupload.ts
  src/app/showcase/components/fileupload/fileuploaddemo.html
Labels: new feature

#11870 fix(primeng/confirmPopup): fix visible for different target
  src/app/components/confirmpopup/confirmpopup.ts
Labels: pending-review

#11747 fix: Fixed autocomplete empty message in the documentation
  src/app/showcase/components/autocomplete/autocompletedemo.html
Labels: pending-review

#11728 Add TieredMenu onShow / onHide events (fix #11727)
  src/app/components/tieredmenu/tieredmenu.ts
  src/app/showcase/components/tieredmenu/tieredmenudemo.html
Labels: new feature, pending-review

#11883 GalleriaItem activeItem getter to avoid stale references
  src/app/components/galleria/galleria.ts
Labels: enhancement, pending-review

#11877 Update inputswitch.ts
  src/app/components/inputswitch/inputswitch.ts
Labels: pending-review

#11869 Table: Catch exception if multiSortMeta array is empty
  src/app/components/table/table.ts
  src/app/components/treetable/treetable.ts
Labels: pending-review

#11833 range slider fix
  src/app/components/slider/slider.ts
Labels: pending-review

#11813 Fix #11645: don't clear value if editable dropdown's value is not in …
  src/app/components/dropdown/dropdown.ts
Labels: pending-review

#11767 add p-inputtext class to cascadeSelect component
  src/app/components/cascadeselect/cascadeselect.ts
Labels: pending-review

#11666 Generic data property of DynamicDialogConfig
  src/app/components/dynamicdialog/dynamicdialog-config.ts
Labels: pending-review

#11935 Fixed #11924 - Table Sticky headers fail to stick when a table is pla…
  src/app/components/accordion/accordion.css
Labels: need revision

#11936 Fix typos in changelog
  CHANGELOG.md
Labels: need revision

#11986 Fixed #11985 - Add flex-gap to p-chips and p-autocomplete multiple input container
  src/app/components/multiselect/multiselect.css
  src/assets/components/themes/arya-blue/theme.css
  src/assets/components/themes/arya-green/theme.css
  src/assets/components/themes/arya-orange/theme.css
  src/assets/components/themes/arya-purple/theme.css
  src/assets/components/themes/bootstrap4-dark-blue/theme.css
  src/assets/components/themes/bootstrap4-dark-purple/theme.css
  src/assets/components/themes/bootstrap4-light-blue/theme.css
  src/assets/components/themes/bootstrap4-light-purple/theme.css
  src/assets/components/themes/fluent-light/theme.css
  src/assets/components/themes/lara-dark-blue/theme.css
  src/assets/components/themes/lara-dark-indigo/theme.css
  src/assets/components/themes/lara-dark-purple/theme.css
  src/assets/components/themes/lara-dark-teal/theme.css
  src/assets/components/themes/lara-light-blue/theme.css
  src/assets/components/themes/lara-light-indigo/theme.css
  src/assets/components/themes/lara-light-purple/theme.css
  src/assets/components/themes/lara-light-teal/theme.css
  src/assets/components/themes/luna-amber/theme.css
  src/assets/components/themes/luna-blue/theme.css
  src/assets/components/themes/luna-green/theme.css
  src/assets/components/themes/luna-pink/theme.css
  src/assets/components/themes/md-dark-deeppurple/theme.css
  src/assets/components/themes/md-dark-indigo/theme.css
  src/assets/components/themes/md-light-deeppurple/theme.css
  src/assets/components/themes/md-light-indigo/theme.css
  src/assets/components/themes/mdc-dark-deeppurple/theme.css
  src/assets/components/themes/mdc-dark-indigo/theme.css
  src/assets/components/themes/mdc-light-deeppurple/theme.css
  src/assets/components/themes/mdc-light-indigo/theme.css
  src/assets/components/themes/nova-accent/theme.css
  src/assets/components/themes/nova-alt/theme.css
  src/assets/components/themes/nova/theme.css
  src/assets/components/themes/rhea/theme.css
  src/assets/components/themes/saga-blue/theme.css
  src/assets/components/themes/saga-green/theme.css
  src/assets/components/themes/saga-orange/theme.css
  src/assets/components/themes/saga-purple/theme.css
  src/assets/components/themes/tailwind-light/theme.css
  src/assets/components/themes/vela-blue/theme.css
  src/assets/components/themes/vela-green/theme.css
  src/assets/components/themes/vela-orange/theme.css
  src/assets/components/themes/vela-purple/theme.css
Labels: need revision

#11994 Fixed #11982 - TreeSelect | Add styleClass and style support for cont…
  src/app/components/treeselect/treeselect.ts
  src/app/showcase/components/treeselect/treeselectdemo.html
Labels: need revision
