Repository primefaces/primeng, pull requests merged in 2023-06, with the labels that each got.

#13179 Fix 13159 - PrimeNG Website - Documentation for Toast missing positio…
  src/app/showcase/doc/toast/positiondoc.ts
Labels: Resolution: Needs Revision

#13178 Fix #13177 - Icons: clipPath improvements
  src/app/components/icons/arrowdown/arrowdown.ts
  src/app/components/icons/arrowleft/arrowleft.ts
  src/app/components/icons/arrowup/arrowup.ts
  src/app/components/icons/ban/ban.ts
  src/app/components/icons/exclamationtriangle/exclamationtriangle.ts
  src/app/components/icons/eyeslash/eyeslash.ts
  src/app/components/icons/filter/filter.ts
  src/app/components/icons/filterslash/filterslash.ts
  src/app/components/icons/home/home.ts
  src/app/components/icons/infocircle/infocircle.ts
  src/app/components/icons/pencil/pencil.ts
  src/app/components/icons/plus/plus.ts
  src/app/components/icons/refresh/refresh.ts
  src/app/components/icons/search/search.ts
  src/app/components/icons/searchminus/searchminus.ts
  src/app/components/icons/searchplus/searchplus.ts
  src/app/components/icons/sortalt/sortalt.ts
  src/app/components/icons/sortamountdown/sortamountdown.ts
  src/app/components/icons/sortamountupalt/sortamountupalt.ts
  src/app/components/icons/spinner/spinner.ts
  src/app/components/icons/star/star.ts
  src/app/components/icons/starfill/starfill.ts
  src/app/components/icons/thlarge/thlarge.ts
  src/app/components/icons/timescircle/timescircle.ts
  src/app/components/icons/trash/trash.ts
  src/app/components/icons/undo/undo.ts
  src/app/components/icons/upload/upload.ts
  src/app/components/icons/windowmaximize/windowmaximize.ts
  src/app/components/icons/windowminimize/windowminimize.ts
Labels: Resolution: Needs Revision

#13137 Fix #13129 - FileUpload | File limit does not fire error
  src/app/components/fileupload/fileupload.ts
Labels: Resolution: Needs Revision

#13215 Fix #13201 - OverlayPanel: Incorrect position when inside of dialog i…
  src/app/components/overlaypanel/overlaypanel.ts
Labels: Resolution: Needs Revision

#13019 Update dynamicdialog-config.ts
  src/app/components/dynamicdialog/dynamicdialog-config.ts
Labels: Type: Enhancement

#13219 🚀 chore(menu.ts): export SafeHtmlPipe class to be able to use it
  src/app/components/menu/menu.ts
Labels: good first issue

#12638 resolves #12637 -- uses proper group children property in dropdown autoselect
  src/app/components/dropdown/dropdown.spec.ts
  src/app/components/dropdown/dropdown.ts
Labels: Status: Pending Review
