Repository primefaces/primeng, pull requests merged in 2023-08, with the labels that each got.

#13432 Bugfix #13431 Fix accordion accessibility
  src/app/components/accordion/accordion.ts
  src/app/showcase/doc/accordion/accessibilitydoc.ts
Labels: Resolution: Needs Revision

#13436 Bugfix #13435 Fix PanelMenu tab navigation
  src/app/components/panelmenu/panelmenu.ts
Labels: Resolution: Needs Revision

#11476 Editable Column: do not exit mode on shift enter
  src/app/components/table/table.ts
  src/app/components/treetable/treetable.ts
Labels: Status: Pending Review

#11020 Pass autocomplete attribute into input element
  src/app/components/password/password.ts
Labels: Resolution: Needs Revision

#12154 In primeng calendar, date can be lined through or disabled using date… there is no way to disable years
  src/app/components/calendar/calendar.ts
Labels: Resolution: Needs Revision

#12721 Fix issue 12713 - Toggleable Panel inside another toggleable panel
  src/app/components/panel/panel.css
Labels: Status: Pending Review

#12797 Fixed #12775: p-multiSelect - Check selection limit when limit changes
  src/app/components/multiselect/multiselect.ts
Labels: Resolution: Needs Revision

#12805 Feature #3496: Tooltip optionally take a TemplateRef
  src/app/components/tooltip/tooltip.ts
  src/app/showcase/doc/apidoc/index.json
  src/app/showcase/doc/tooltip/templatedoc.ts
  src/app/showcase/doc/tooltip/tooltipdoc.module.ts
  src/app/showcase/pages/tooltip/tooltipdemo.ts
Labels: Resolution: Needs Revision

#12898 [04152023] | [dONE] | Add locale property to paginator component and …
  src/app/components/paginator/paginator.ts
  src/app/components/table/table.ts
  src/app/components/treetable/treetable.ts
  src/app/showcase/doc/paginator/localedoc.ts
  src/app/showcase/doc/paginator/paginatordoc.module.ts
  src/app/showcase/doc/table/paginatorlocaledoc.ts
  src/app/showcase/doc/table/tabledoc.module.ts
  src/app/showcase/doc/treetable/paginatorlocaledoc.ts
  src/app/showcase/doc/treetable/treetabledoc.module.ts
  src/app/showcase/pages/paginator/paginatordemo.ts
  src/app/showcase/pages/table/tabledemo.ts
  src/app/showcase/pages/treetable/treetabledemo.ts
Labels: Resolution: Needs Revision

#13548 Fix #13522 - SplitButton [NG]: Menu is not closing when click on outside
  src/app/components/tieredmenu/tieredmenu.ts
Labels: Resolution: Needs Revision

#12283 Add appendTo to Dynamic Dialog
  src/app/components/dynamicdialog/dialogservice.ts
  src/app/components/dynamicdialog/dynamicdialog-config.ts
Labels: Resolution: Needs Revision

#13550 [FIX] removed duplicated "inputId" attribuite.
  src/app/showcase/doc/inputnumber/numeralsdoc.ts
Labels: Resolution: Needs Revision

#13349 [#13348] - Fixed calendar component, added yearOptions onInit
  src/app/components/calendar/calendar.ts
Labels: Status: Pending Review

#13010 Modify refactor selectButton
  src/app/components/selectbutton/selectbutton.ts
Labels: Resolution: Needs Issue

#13205 feat: Add custom style class to p-table p-dataview p-treeview
  src/app/components/dataview/dataview.ts
  src/app/components/table/table.ts
  src/app/components/treetable/treetable.ts
Labels: Resolution: Needs Revision

#13564 fix: #13560 || DropDown clear or close icon on click dropDown option show
  src/app/components/dropdown/dropdown.ts
Labels: Status: Pending Review

#13392 Fix for incorrect behaviour when a column is both sortable and filter…
  src/app/components/table/table.ts
Labels: Status: Pending Review
