Repository primefaces/primeng, pull requests merged in 2023-04, with the labels that each got.

#12843 Fix: #12842 MultiSelect | Add gap and text ellipsis to multiselect-chip
  src/app/components/multiselect/multiselect.css
  src/assets/components/themes/arya-blue/theme.css
  src/assets/components/themes/arya-green/theme.css
  src/assets/components/themes/arya-orange/theme.css
  src/assets/components/themes/arya-purple/theme.css
  src/assets/components/themes/bootstrap4-dark-blue/theme.css
  src/assets/components/themes/bootstrap4-dark-purple/theme.css
  src/assets/components/themes/bootstrap4-light-blue/theme.css
  src/assets/components/themes/bootstrap4-light-purple/theme.css
  src/assets/components/themes/fluent-light/theme.css
  src/assets/components/themes/lara-dark-blue/theme.css
  src/assets/components/themes/lara-dark-indigo/theme.css
  src/assets/components/themes/lara-dark-purple/theme.css
  src/assets/components/themes/lara-dark-teal/theme.css
  src/assets/components/themes/lara-light-blue/theme.css
  src/assets/components/themes/lara-light-indigo/theme.css
  src/assets/components/themes/lara-light-purple/theme.css
  src/assets/components/themes/lara-light-teal/theme.css
  src/assets/components/themes/luna-amber/theme.css
  src/assets/components/themes/luna-blue/theme.css
  src/assets/components/themes/luna-green/theme.css
  src/assets/components/themes/luna-pink/theme.css
  src/assets/components/themes/md-dark-deeppurple/theme.css
  src/assets/components/themes/md-dark-indigo/theme.css
  src/assets/components/themes/md-light-deeppurple/theme.css
  src/assets/components/themes/md-light-indigo/theme.css
  src/assets/components/themes/mdc-dark-deeppurple/theme.css
  src/assets/components/themes/mdc-dark-indigo/theme.css
  src/assets/components/themes/mdc-light-deeppurple/theme.css
  src/assets/components/themes/mdc-light-indigo/theme.css
  src/assets/components/themes/mira/theme.css
  src/assets/components/themes/nano/theme.css
  src/assets/components/themes/nova-accent/theme.css
  src/assets/components/themes/nova-alt/theme.css
  src/assets/components/themes/nova/theme.css
  src/assets/components/themes/rhea/theme.css
  src/assets/components/themes/saga-blue/theme.css
  src/assets/components/themes/saga-green/theme.css
  src/assets/components/themes/saga-orange/theme.css
  src/assets/components/themes/saga-purple/theme.css
  src/assets/components/themes/soho-dark/theme.css
  src/assets/components/themes/soho-light/theme.css
  src/assets/components/themes/tailwind-light/theme.css
  src/assets/components/themes/vela-blue/theme.css
  src/assets/components/themes/vela-green/theme.css
  src/assets/components/themes/vela-orange/theme.css
  src/assets/components/themes/vela-purple/theme.css
  src/assets/components/themes/viva-dark/theme.css
  src/assets/components/themes/viva-light/theme.css
Labels: Resolution: Needs Revision

#12850 CMD key triggering re-highlight
  src/app/showcase/layout/doc/code/app.code.component.ts
Labels: Status: Pending Review

#12853 Fix Issue 12493: Last slot of reorderable table breaks when page is scrolled
  src/app/components/table/table.ts
Labels: Type: Bug, LTS-PORTABLE

#12904 Fix clear function not resetting all filters
  src/app/components/table/table.ts
Labels: Status: Pending Review
