Repository primefaces/primeng, pull requests merged in 2023-09, with the labels that each got.

#13587 fix: #13571 | Multiselect not repositioned
  src/app/components/multiselect/multiselect.ts
Labels: Status: Pending Review

#13647 Fix #13646 dynamic dialog module same instances on top of each other/get rid of deprecated implementation
  src/app/components/dynamicdialog/dialogservice.ts
  src/app/components/dynamicdialog/dynamicdialog-config.ts
  src/app/components/dynamicdialog/dynamicdialog-injector.ts
  src/app/components/dynamicdialog/dynamicdialog.ts
Labels: Type: Enhancement

#13644 dialog: Possible fix ExpressionChangedAfterItHasBeenCheckedError with attr.aria-labelledby
  src/app/components/dialog/dialog.ts
Labels: Status: Pending Review, Resolution: Needs Revision
