Repository primefaces/primeng, pull requests merged in 2024-11, with the labels that each got.

#16391 Fix indexing in the p-tree so drag and drop will work with virtual scroll.
  src/app/components/api/treenode.ts
  src/app/components/tree/tree.ts
Labels: Status: Pending Review

#16174 Add a boolean which indicates if the drop is in a drop point or a node
  src/app/components/tree/tree.interface.ts
  src/app/components/tree/tree.ts
Labels: Type: Enhancement, Type: New Feature, good first issue

#15763 feat(chips): added onChipContextMenu output analog to onChipClick
  src/app/components/chips/chips.interface.ts
  src/app/components/chips/chips.ts
  src/app/showcase/doc/apidoc/index.json
Labels: Status: Discussion, Resolution: Needs Revision

#16735 fix(table): column resize does not work with sortable columns
  src/app/components/table/table.ts
Labels: Resolution: Needs Revision

#16643 fix(docs): typo in theming#component
  apps/showcase/doc/theming/componentdoc.ts
Labels: Resolution: Needs Revision, Component: Documentation

#16644 fix(docs): removes extra spacing and renames "warning" to "warn"
  apps/showcase/doc/button/iconsonlydoc.ts
Labels: Resolution: Needs Revision
