Repository primefaces/primeng, pull requests merged in 2024-05, with the labels that each got.

#15491 Fixed #15490 - InputSwitch | Accessibility issue changing the inputsw…
  src/app/components/inputswitch/inputswitch.ts
Labels: Resolution: Needs Revision

#15469 Fixed #15468 - Tooltip | tooltipEvent - focus | hover combined
  src/app/components/tooltip/tooltip.ts
Labels: Resolution: Needs Revision

#15451 Improve calendar keyboard accessibility
  src/app/components/calendar/calendar.ts
Labels: Status: Pending Review, Status: Discussion

#15561 Issue 15560 - Introduces csp none
  src/app/components/api/primengconfig.ts
  src/app/components/calendar/calendar.ts
  src/app/components/carousel/carousel.ts
  src/app/components/confirmdialog/confirmdialog.ts
  src/app/components/dialog/dialog.ts
  src/app/components/dynamicdialog/dynamicdialog.ts
  src/app/components/galleria/galleria.ts
  src/app/components/orderlist/orderlist.ts
  src/app/components/picklist/picklist.ts
  src/app/components/table/table.ts
  src/app/components/toast/toast.ts
  src/app/showcase/doc/button/templatedoc.ts
  src/app/showcase/doc/configuration/configurationdoc.module.ts
  src/app/showcase/doc/configuration/cspdoc.ts
  src/app/showcase/pages/configuration/configurationdemo.component.ts
Labels: Resolution: Needs Revision

#15547 Fixed #15546 - Galleria | Keyboard Trap within Galleria component
  src/app/components/focustrap/focustrap.ts
  src/app/components/galleria/galleria.css
  src/app/components/galleria/galleria.ts
Labels: Resolution: Needs Revision

#15559 Panelmenu Update
  src/app/components/panelmenu/panelmenu.ts
  src/app/showcase/doc/panelmenu/routerdoc.ts
  src/app/showcase/doc/panelmenu/templatedoc.ts
Labels: Resolution: Needs Revision

#15558 Fixed #15545 - Tooltip visual issue
  src/app/components/tooltip/tooltip.ts
Labels: Resolution: Needs Revision

#15447 fix: tieredMenuSub improve self-positioning in viewPort when viewPort…
  src/app/components/tieredmenu/tieredmenu.ts
Labels: Resolution: Needs Revision

#15587 Fixed #15390 - Button/p-button and tooltip: Doesn't work correctly
  src/app/components/tooltip/tooltip.ts
Labels: Resolution: Needs Revision

#15575 Fixed #15175 - Stepper | linear does not work with header template
  src/app/showcase/doc/stepper/templatedoc.ts
Labels: Resolution: Needs Revision

#15569 #15293 fixed inputNumber selection lost when selecting left prefix
  src/app/components/inputnumber/inputnumber.ts
Labels: good first issue

#15728 FIX:PasswordDirective loss PrimeNGConfig in constructor
  src/app/components/password/password.ts
Labels: good first issue

#15667 Table: Reorderable column false still gives cursor move
  src/app/components/table/table.css
  src/app/components/table/table.ts
Labels: Resolution: Needs Revision
