Repository primefaces/primeng, pull requests merged in 2024-12, with the labels that each got.

#16796 Fix: Menu(16795): appendChild param order reversed
  packages/primeng/src/drawer/drawer.ts
  packages/primeng/src/menu/menu.ts
  packages/primeng/src/overlaypanel/overlaypanel.ts
  packages/primeng/src/popover/popover.ts
  packages/primeng/src/sidebar/sidebar.ts
  packages/primeng/src/tieredmenu/tieredmenu.ts
Labels: Status: Pending Review

#16816 Fix:16755 - dropdown emit event
  src/app/components/dropdown/dropdown.ts
Labels: Status: Pending Review

#16808 Fix: Multiselect & Autocomplete(#16708 & #16727) - Scroller panel height bug
  src/app/components/scroller/scroller.ts
Labels: Status: Pending Review

#16790 Fix: PanelMenu(15403) - Submenu displays angledownicon when submenu is collapsed
  src/app/components/panelmenu/panelmenu.ts
Labels: Status: Pending Review

#16787 Fix #16744: Prevent click event from triggering on disabled p-toggleButton
  src/app/components/togglebutton/togglebutton.ts
Labels: Status: Pending Review

#16685 fix: #16684, MultiSelect: Unable to select remove icon of chips through keyboard
  src/app/components/multiselect/multiselect.ts
Labels: Status: Pending Review

#16655 Issue 16653 tab fix
  src/app/components/inputotp/inputotp.ts
Labels: Resolution: Needs Revision

#16556 fix: #16555, Password: Tab navigation not getting focussed on Eye icon in ToggleMask Mode.
  src/app/components/password/password.ts
Labels: Status: Discussion

#16383 Accept the locale for the file size of the format
  src/app/components/fileupload/fileupload.ts
Labels: Status: Pending Review

#16232 Fix #14529 - Google Gboard and inputmask control
  src/app/components/inputmask/inputmask.ts
Labels: Status: Pending Review

#16531 fixed issue #16313 (p-tabview closing active first tab opens not the next tab)
  src/app/components/tabview/tabview.ts
Labels: Status: Pending Review

#16896 Fixed #16892 - Showcase | Table of Contents not updating on scroll
  apps/showcase/components/doc/app.docsection-nav.component.ts
Labels: Status: Pending Review

#17172 fix: #17171 Fix tree inline style overridde
  packages/primeng/src/tree/tree.ts
Labels: Status: Discussion

#17123 Fix: Dynamic Dialog not being properly destroyed on close
  packages/primeng/src/dynamicdialog/dialogservice.ts
Labels: Status: Discussion
