Repository primefaces/primeng, pull requests merged in 2024-03, with the labels that each got.

#14959 Fixed #14865 - Dropdown | TypeError: this.getOptionLabel(...).toLocal…
  src/app/components/dropdown/dropdown.ts
Labels: Resolution: Needs Revision

#14961 Fixed #14960 - Multiselect | TypeError: option.toLocaleLowerCase is n…
  src/app/components/multiselect/multiselect.ts
Labels: Resolution: Needs Revision

#14943 Fixed #14942 - Only showing first parameter
  src/app/showcase/layout/doc/app.docapisection.component.ts
  src/app/showcase/layout/doc/app.docapitable.component.ts
Labels: Status: Pending Review

#14964 fixes #14962 - ContextMenu | onHide, onShow event is not being triggered when you right click twice continuously
  src/app/components/contextmenu/contextmenu.ts
  src/app/components/table/table.ts
Labels: Status: Pending Review, Resolution: Needs Revision, Resolution: Needs Issue

#15025 fix #15024 table filter row aria-labels
  src/app/components/table/table.ts
  src/app/showcase/doc/table/filterrowdoc.ts
Labels: Resolution: Needs Revision

#15106 Fixed #14888 - Remove extra conditional
  src/app/components/table/table.ts
Labels: Resolution: Needs Revision

#14957 feat: Dynamic dialog. Child component reference to be able to
  src/app/components/dynamicdialog/dialogservice.ts
  src/app/components/dynamicdialog/dynamicdialog-ref.ts
  src/app/components/dynamicdialog/dynamicdialog.ts
Labels: Resolution: Needs Revision

#14754 Feat: calendar - enable minDate & maxDate to be nullable
  src/app/components/calendar/calendar.ts
Labels: Status: Pending Review

#15156 Fixed #14949 - Dialog | Missing Aria Label on Maximize button
  src/app/components/api/primengconfig.ts
  src/app/components/api/translation.ts
  src/app/components/dialog/dialog.ts
Labels: Resolution: Needs Revision

#15163 Fixed #15084 - Listbox | Missing aria-label
  src/app/components/listbox/listbox.ts
Labels: Resolution: Needs Revision

#15162 Fixed #15122 - Dropdown | Missing ariaLabel when in editable = true
  src/app/components/dropdown/dropdown.ts
Labels: Resolution: Needs Revision

#14771 Fixed #14770 - api-generator problem
  api-generator/build-apidoc.ts
  package.json
  src/app/components/api/messageservice.ts
  src/app/showcase/doc/apidoc/index.json
Labels: Resolution: Needs Revision

#15174 Fixed #15173 - Stepper | Update broken styles of stepper
  src/assets/components/themes/arya-blue/theme.css
  src/assets/components/themes/arya-green/theme.css
  src/assets/components/themes/arya-orange/theme.css
  src/assets/components/themes/arya-purple/theme.css
  src/assets/components/themes/bootstrap4-dark-blue/theme.css
  src/assets/components/themes/bootstrap4-dark-purple/theme.css
  src/assets/components/themes/bootstrap4-light-blue/theme.css
  src/assets/components/themes/bootstrap4-light-purple/theme.css
  src/assets/components/themes/fluent-light/theme.css
  src/assets/components/themes/lara-dark-blue/theme.css
  src/assets/components/themes/lara-dark-indigo/theme.css
  src/assets/components/themes/lara-dark-purple/theme.css
  src/assets/components/themes/lara-dark-teal/theme.css
  src/assets/components/themes/lara-light-blue/theme.css
  src/assets/components/themes/lara-light-indigo/theme.css
  src/assets/components/themes/lara-light-purple/theme.css
  src/assets/components/themes/lara-light-teal/theme.css
  src/assets/components/themes/luna-amber/theme.css
  src/assets/components/themes/luna-blue/theme.css
  src/assets/components/themes/luna-green/theme.css
  src/assets/components/themes/luna-pink/theme.css
  src/assets/components/themes/md-dark-deeppurple/theme.css
  src/assets/components/themes/md-dark-indigo/theme.css
  src/assets/components/themes/md-light-deeppurple/theme.css
  src/assets/components/themes/md-light-indigo/theme.css
  src/assets/components/themes/mdc-dark-deeppurple/theme.css
  src/assets/components/themes/mdc-dark-indigo/theme.css
  src/assets/components/themes/mdc-light-deeppurple/theme.css
  src/assets/components/themes/mdc-light-indigo/theme.css
  src/assets/components/themes/mira/theme.css
  src/assets/components/themes/nano/theme.css
  src/assets/components/themes/nova-accent/theme.css
  src/assets/components/themes/nova-alt/theme.css
  src/assets/components/themes/nova/theme.css
  src/assets/components/themes/rhea/theme.css
  src/assets/components/themes/saga-blue/theme.css
  src/assets/components/themes/saga-green/theme.css
  src/assets/components/themes/saga-orange/theme.css
  src/assets/components/themes/saga-purple/theme.css
  src/assets/components/themes/soho-dark/theme.css
  src/assets/components/themes/soho-light/theme.css
  src/assets/components/themes/tailwind-light/theme.css
  src/assets/components/themes/vela-blue/theme.css
  src/assets/components/themes/vela-green/theme.css
  src/assets/components/themes/vela-orange/theme.css
  src/assets/components/themes/vela-purple/theme.css
  src/assets/components/themes/viva-dark/theme.css
  src/assets/components/themes/viva-light/theme.css
Labels: Resolution: Needs Revision

#15166 Fixed #15123 - Dropdown | Dropdown box missing the required children …
  src/app/components/dropdown/dropdown.ts
Labels: Resolution: Needs Revision
