Repository primefaces/primeng, pull requests merged in 2024-07, with the labels that each got.

#15764 Fixed Issue #14721 (Add support for Quill 2.0)
  src/app/components/editor/editor.ts
Labels: Type: Enhancement, dependencies

#15945 fix(splitter): resize not working when iFrames are used in panels
  src/app/components/splitter/splitter.css
Labels: good first issue

#15631 add `p-disabled` to the chip icon if option is disabled
  src/app/components/multiselect/multiselect.ts
Labels: Resolution: Needs Revision

#15955 Fixed #15869 - CascadeSelect | clicking a few times causes the compon…
  src/app/components/overlay/overlay.ts
Labels: Resolution: Needs Revision

#16041 fix(MultiSelect): Check for NaN values in isSelectionAllDisabled method
  src/app/components/multiselect/multiselect.ts
Labels: Resolution: Needs Revision

#15982 Fixed #15973 - TabMenu doesn't scroll to active item when it's set pr…
  src/app/components/tabmenu/tabmenu.ts
  src/app/showcase/pages/tabmenu/tabmenudemo.ts
Labels: Resolution: Needs Revision

#15927 Fixed #15876 - TreeTable: Resizing one column resizes other columns a…
  src/app/components/treetable/treetable.ts
Labels: Resolution: Needs Revision

#16021 fixes #16020 Table: column-filter outside click does not close when it is inside a dialog component
  src/app/components/table/table.ts
Labels: Resolution: Needs Revision
