Repository primefaces/primeng, pull requests merged in 2024-04, with the labels that each got.

#15203 Fixed #15200 - backspace key doesn't work @ Template
  src/app/components/inputotp/inputotp.ts
  src/app/showcase/doc/inputotp/sampledoc.ts
  src/app/showcase/doc/inputotp/templatedoc.ts
Labels: Resolution: Needs Revision

#15235 New template page
  package-lock.json
  src/app/showcase/layout/templates/templateconfiguration.ts
  src/app/showcase/layout/templates/templatefeatures.ts
  src/app/showcase/layout/templates/templatefeaturesanimation/templatefeaturesanimation.ts
  src/app/showcase/layout/templates/templatefeaturesanimation/templatefeaturesanimationinline.ts
  src/app/showcase/layout/templates/templatehero/templatehero.ts
  src/app/showcase/layout/templates/templatehero/templateherolight.ts
  src/app/showcase/layout/templates/templatehero/templateherorectangle.ts
  src/app/showcase/layout/templates/templatelicense.ts
  src/app/showcase/layout/templates/templaterelated.ts
  src/app/showcase/layout/templates/templateseparator.ts
  src/app/showcase/layout/templates/templateyoutube.ts
  src/app/showcase/pages/templates/apollo/apollo.ts
  src/app/showcase/pages/templates/apollo/apollologo.ts
  src/app/showcase/pages/templates/apollo/apolloseparator.ts
  src/app/showcase/pages/templates/atlantis/atlantis.ts
  src/app/showcase/pages/templates/atlantis/atlantislogo.ts
  src/app/showcase/pages/templates/atlantis/atlantisseparator.ts
  src/app/showcase/pages/templates/avalon/avalon.ts
  src/app/showcase/pages/templates/avalon/avalonlogo.ts
  src/app/showcase/pages/templates/avalon/avalonseparator.ts
  src/app/showcase/pages/templates/diamond/diamond.ts
  src/app/showcase/pages/templates/diamond/diamondlogo.ts
  src/app/showcase/pages/templates/diamond/diamondseparator.ts
  src/app/showcase/pages/templates/freya/freya.ts
  src/app/showcase/pages/templates/freya/freyalogo.ts
  src/app/showcase/pages/templates/freya/freyaseparator.ts
  src/app/showcase/pages/templates/learnmore/learnmore-routing.module.ts
  src/app/showcase/pages/templates/learnmore/learnmore.component.html
  src/app/showcase/pages/templates/learnmore/learnmore.component.ts
  src/app/showcase/pages/templates/learnmore/learnmore.module.ts
  src/app/showcase/pages/templates/learnmore/learnmore.scss
  src/app/showcase/pages/templates/learnmore/templatedata.json
  src/app/showcase/pages/templates/poseidon/poseidon.ts
  src/app/showcase/pages/templates/poseidon/poseidonlogo.ts
  src/app/showcase/pages/templates/poseidon/poseidonseparator.ts
  src/app/showcase/pages/templates/sakai/sakai.ts
  src/app/showcase/pages/templates/sakai/sakailogo.ts
  src/app/showcase/pages/templates/sakai/sakaiseparator.ts
  src/app/showcase/pages/templates/templates-routing.module.ts
  src/app/showcase/pages/templates/templates.component.html
  src/app/showcase/pages/templates/templates.module.ts
  src/app/showcase/pages/templates/ultima/ultima.ts
  src/app/showcase/pages/templates/ultima/ultimalogo.ts
  src/app/showcase/pages/templates/ultima/ultimaseparator.ts
  src/app/showcase/pages/templates/verona/verona.ts
  src/app/showcase/pages/templates/verona/veronalogo.ts
  src/app/showcase/pages/templates/verona/veronaseparator.ts
  src/index.html
Labels: Resolution: Needs Revision

#15172 Fixed #15115 - Component | pDropdown wrapper
  src/app/components/dropdown/dropdown.ts
Labels: Status: Discussion, Resolution: Needs Revision

#15275 fix: #15264 use null as fallbackValue for input transform of minFractionDigits and maxFractionDigits
  src/app/components/inputnumber/inputnumber.ts
  src/app/components/table/table.ts
Labels: Type: Bug

#15263 Fix #14010, #13162, #13768, #13082, #10472
  src/app/components/autofocus/autofocus.ts
  src/app/components/button/button.ts
  src/app/components/calendar/calendar.ts
  src/app/components/cascadeselect/cascadeselect.ts
  src/app/components/checkbox/checkbox.ts
  src/app/components/chips/chips.ts
  src/app/components/colorpicker/colorpicker.ts
  src/app/components/dialog/dialog.ts
  src/app/components/dom/domhandler.ts
  src/app/components/dropdown/dropdown.ts
  src/app/components/dynamicdialog/dynamicdialog-config.ts
  src/app/components/dynamicdialog/dynamicdialog.ts
  src/app/components/inputmask/inputmask.ts
  src/app/components/inputnumber/inputnumber.ts
  src/app/components/inputotp/inputotp.ts
  src/app/components/inputswitch/inputswitch.ts
  src/app/components/multiselect/multiselect.ts
  src/app/components/password/password.ts
  src/app/components/radiobutton/radiobutton.ts
  src/app/components/rating/rating.ts
  src/app/components/selectbutton/selectbutton.ts
  src/app/components/slider/slider.ts
  src/app/components/splitbutton/splitbutton.ts
  src/app/components/togglebutton/togglebutton.ts
  src/app/components/treeselect/treeselect.ts
  src/app/components/tristatecheckbox/tristatecheckbox.ts
  src/app/showcase/doc/apidoc/index.json
  src/app/showcase/doc/calendar/propsdoc.ts
Labels: Status: Pending Review

#15280 Fixed #15233 - Dropdown | Dropdown in Table Filter Menu Fails to Appl…
  src/app/components/table/table.ts
Labels: Resolution: Needs Revision

#15300 Fixed #15233 | Refactor condition for outsideClick
  src/app/components/table/table.ts
Labels: Resolution: Needs Revision

#12739 feat(primeng/p-badge): rework dynamic property rerender for directive
  src/app/components/badge/badge.ts
  src/app/showcase/doc/apidoc/index.json
  src/app/showcase/doc/badge/sizedoc.ts
Labels: Status: Pending Review, Status: Discussion, Type: Breaking Change

#15302 Fix Issue with frozen columns #12408
  src/app/components/table/table.ts
Labels: Status: Pending Review

#15376 Revert typo & fix #15306
  src/app/components/table/table.ts
  src/app/showcase/doc/apidoc/index.json
Labels: Resolution: Needs Revision

#15309 feature(autocomplete): Add optionValue input
  src/app/components/autocomplete/autocomplete.ts
Labels: Status: Pending Review
